web/router.ex
defmodule Greenfitdiety.Router do
  use Greenfitdiety.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Greenfitdiety.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Greenfitdiety do
    pipe_through :browser # Use the default browser stack
    get "/", AuthController, :start
    get "/login", AuthController, :login_page
    post "/login", AuthController, :login_with_password
    get "/password", UserController, :password
    get "/contact", UserController, :contact
    get "/users/:id/settings", UserController, :settings
    post "/users/:id/password", UserController, :update_password
    resources "/users", UserController
    resources "/users/:user_id/diets", DietController
    resources "/users/:user_id/changes", ChangeController
  end

  scope "/auth", Greenfitdiety do
    pipe_through :browser
    get "/api_login", AuthController, :api_login
    get "/notallowed", AuthController, :notallowed
    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/api", Greenfitdiety do
    pipe_through :api
    get "/users", UserController, :users_api
    get "/users/:id", UserController, :user_api
    get "/users/:user_id/diets", DietController, :diets_api
    get "/users/:user_id/diets/:id", DietController, :diet_api
    get "/users/:user_id/changes", ChangeController, :changes_api
    get "/users/:user_id/changes/:id", ChangeController, :change_api
    get "/empty", UserController, :empty
  end
end

web/models/user.ex
defmodule Greenfitdiety.User do
  use Greenfitdiety.Web, :model

  schema "users" do
    field       :email,             :string, size: 50
    field       :password,          :string, default: "F8EB2D747726901A7E81D44D0F7C9AEEDD"
    field       :provider,          :string, size: 25
    field       :token,             :string
    field       :first_name,        :string, size: 25
    field       :last_name,         :string, size: 25
    field       :phone,             :string, size: 20
    field       :weight,            :integer
    field       :height,            :integer
    field       :age,               :integer
    field       :metabolic_age,     :integer
    field       :fat,               :integer
    field       :visceral_fat,      :integer
    field       :avatar,            :binary
    field       :role,              :string, size: 20, default: "brak"
    has_many    :diets,             Greenfitdiety.Diet, on_delete: :delete_all
    has_many    :changes,           Greenfitdiety.Change, on_delete: :delete_all
    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email,
                     :password,
                     :provider,
                     :token,
                     :first_name,
                     :last_name,
                     :phone,
                     :weight,
                     :height,
                     :age,
                     :metabolic_age,
                     :fat,
                     :visceral_fat,
                     :avatar,
                     :role])
    |> validate_required([:email])
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/@/)
    |> validate_length(:email, min: 3)
    |> validate_length(:password, min: 5)
  end

end

web/controllers/user_controller.ex
defmodule Greenfitdiety.UserController do
  use Greenfitdiety.Web, :controller
  alias Greenfitdiety.User
  plug Greenfitdiety.Plugs.RequireAuth when action in [:index, :new, :create, :update, :edit, :delete, :show]
  plug Greenfitdiety.Plugs.CheckUserRole when action in [:edit, :update, :delete, :show]
  plug Greenfitdiety.Plugs.CheckUserRoleOnlyAdmin when action in [:new, :create]
  # plug Greenfitdiety.Plugs.AppToken when action in [:users_api, :user_api]
  # plug Greenfitdiety.Plugs.AdminToken when action in [:users_api]
  # plug Greenfitdiety.Plugs.ResourcePremission when action in [:user_api]
  alias Greenfitdiety.AuthController

  def index(conn, _params) do
    users = for user <- Repo.all(User) do
      Map.from_struct user
    end
    user = Repo.get!(User, conn.assigns.user.id)
    render conn, "index.html", users: users, user: user
  end

  def password(conn, _params) do
    render conn, "password.html"
  end

  def contact(conn, _params) do
    render conn, "contact.html"
  end

  def delete(conn, %{"id" => user_id}) do
    Repo.get(User, user_id)
    |> Repo.delete!
    {id, _} = Integer.parse(user_id)
    if id == conn.assigns.user.id do
      conn
      |> put_flash(:info, "Użytkownik usunięty")
      |> redirect(to: auth_path(conn, :signout))
    else
      conn
      |> put_flash(:info, "Użytkownik usunięty")
      |> redirect(to: user_path(conn, :index))
    end
  end

  def show(conn, %{"id" => user_id}) do
    user = Repo.get!(User, user_id)
    render conn, "show.html", user_showed: user
  end

  def edit(conn, %{"id" => user_id}) do
    user = Repo.get!(User, user_id)
    changeset = User.changeset(user)
    render conn, "edit.html", user_edited: user, changeset: changeset
  end

  def update(conn, %{"id" => user_id, "user" => new_user}) do
    old_user = Repo.get(User, user_id)
    setPassword(user_id, new_user["password"])
    new_user = Map.delete(new_user, "password")
    # new_user = if(conn.assigns.user.role=="administrator") do
    #   %{new_user | "password" => AuthController.hash_password(new_user["password"])}
    # end
    changeset = User.changeset(old_user, new_user)
    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Zmiany zostały zapisane")
        |> redirect(to: user_path(conn, :show, user))
      {:error, _reason} ->
        conn
        |> put_flash(:error, "Zmiany nie zostały zapisane")
        |> redirect(to: user_path(conn, :show, old_user))
    end
  end

  def new(conn, _params) do

    case Map.has_key?(conn.assigns, :user) do
      false ->
        conn
        |> put_flash(:error, "Korzystanie z serwisu wymaga zalogowania")
        |> redirect(to: auth_path(conn, :login_page))
      true ->
        changeset = User.changeset(%User{})
        render conn, "new.html", changeset: changeset
    end

  end

  def create(conn, %{"user" => %{"email" => email}}) do
    changeset = User.changeset(%User{}, %{email: email})
    case AuthController.insert_or_update_user(conn, changeset) do
      {:ok, user} ->
        redirect(conn, to: user_path(conn, :edit, user.id))
      {:error, _reason} ->
        conn
        |> put_flash(:error, "Nie udało się zalogować...")
        |> redirect(to: user_path(conn, :index))
    end
  end

  def settings(conn, _params) do
    render conn, "settings.html"
  end

  def update_password(conn, %{"id" => id, "pswchange" => pswchange}) do
    old = conn.assigns.user.password
    case old == AuthController.hash_password(pswchange["old_password"]) do
      true ->
        if pswchange["new_password"] == pswchange["new_password_repeat"] do
          old_user = Repo.get(User, id)
          changeset = User.changeset(old_user, %{password: AuthController.hash_password(pswchange["new_password"])})
          case Repo.update(changeset) do
            {:ok, _user} ->
              conn
              |> put_flash(:info, "Hasło zostało zmienione")
              |> redirect(to: user_path(conn, :show, id))
            {:error, _reason} ->
              conn
              |> put_flash(:error, "Nie udało się zmienić hasła")
              |> redirect(to: user_path(conn, :settings, id))
          end
        else
          conn
          |> put_flash(:error, "Nowe hasła nie są takie same")
          |> redirect(to: user_path(conn, :settings, id))
        end
      false ->
        conn
        |> put_flash(:error, "Niepoprawne stare hasło")
        |> redirect(to: user_path(conn, :settings, id))
    end
  end

  def externalUpdate(conn, user_id, change) do
    old_user = Repo.get(User, user_id)
    changeset = User.changeset(old_user, change)
    Repo.update!(changeset)
  end

  def setPassword(id, password) do
    old_user = Repo.get(User, id)
    if (String.length(password) > 3) do
      changeset = User.changeset(old_user, %{password: AuthController.hash_password(password)})
      Repo.update!(changeset)
    end
  end

  def users_api(conn, _params) do

    get_req_header(conn, "token")
    users = Repo.all(User)
    render(conn, "index.json", users: users)
  end
  def user_api(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    render(conn, "show.json", user: user)
  end

  def empty(conn, _params) do
    render conn, "empty.json"
  end

end

web/views/user_view.ex
defmodule Greenfitdiety.UserView do
  use Greenfitdiety.Web, :view

  def render("index.json", %{users: users}) do
    render_many(users, Greenfitdiety.UserView, "user.json")
  end

  def render("show.json", %{user: user}) do
    render_one(user, Greenfitdiety.UserView, "user.json")
  end

  def render("empty.json", _params) do
    []
  end

  def render("user.json", %{user: user}) do
    %{id:               user.id,
      email:            user.email,
      password:         user.password,
      provider:         user.provider,
      token:            user.token,
      first_name:       user.first_name,
      last_name:        user.last_name,
      phone:            user.phone,
      weight:           user.weight,
      height:           user.height,
      age:              user.age,
      metabolic_age:    user.age,
      fat:              user.fat,
      visceral_fat:     user.visceral_fat,
      avatar:           user.avatar,
      role:             user.role,
      inserted_at:      user.inserted_at,
      updated_at:       user.updated_at
      }
  end

end

web/templates/user/contact.html.eex
<center>

<h3>Aby zostać naszym klientem umów się na wizytę:<br><br></h3>
<h4>
  - przez stronę www:
  <a href="http://greenfitdiety.pl/" target="_blank" style="font-size: 1.8rem; font-weight: bold; color: black">
    greenfitdiety.pl
  </a><br><br>
  - telefonicznie:  <b>500-126-496</b><br><br>
  - mailowo: <b>ula.bulanda92@gmail.com</b><br>
</h4>

</center>

web/templates/user/edit.html.eex
<div class="edit_user">
  <div class="col s12 m7">
    <%= form_for @changeset, user_path(@conn, :update, @user_edited), fn f -> %>
    <h2 class="header white-text">
      Edycja danych użytkownika
    </h2>
    <div class="card horizontal">
      <div class="card-image grey lighten-3 center-align" style="padding: 20px">
        <img src="<%= "/files/avatars/" <> @user_edited.email <> ".png" %>" class="shadow"
         style="margin-left: auto; margin-right: auto;"/><br>
        <span style="font-size: 2.5rem;"><b><%= @user_edited.first_name %> <%= @user_edited.last_name %> </b></span><br>
        <span style="font-size: 2.1rem"><%= @user_edited.email %> </span>
      </div>
        <div class="card-stacked grey lighten-4">

            <div class="card-content">

              <p class="border-bottom-edit">ID:
                <span class="right"><%= @user_edited.id %></span>
              </p>
              <%= if @conn.assigns.user.role == "administrator" do %>
                <p class="border-bottom-edit">Hasło:
                  <span class="right">
                    <%= text_input f, :password, value: "", class: "card_edit_input", placeholder: "Wpisz nowe hasło (minimum 4 znaki)" %>
                    <%= error_tag f, :password %>
                  </span>
                </p>
              <% end %>
              <p class="border-bottom-edit">Telefon:
                <span class="right">
                  <%= text_input f, :phone, value: @user_edited.phone, class: "card_edit_input", placeholder: "to pole jest puste" %>
                  <%= error_tag f, :phone %>
                </span>
              </p>
              <p class="border-bottom-edit">Wzrost:
                <span class="right">
                  <%= text_input f, :height, value: @user_edited.height, class: "card_edit_input", placeholder: "to pole jest puste" %>
                  <%= error_tag f, :height %>
                </span>
              </p>
              <p class="border-bottom-edit">Wiek:
                <span class="right">
                  <%= text_input f, :age, value: @user_edited.age, class: "card_edit_input", placeholder: "to pole jest puste" %>
                  <%= error_tag f, :age %>
                </span>
              </p>
              <p class="border-bottom">Waga: <span class="right"><%= @user_edited.weight %></span></p>
              <p class="border-bottom">Wiek metaboliczny: <span class="right"><%= @user_edited.metabolic_age %></span></p>
              <p class="border-bottom">Zawartość tłuszczu w organiźmie: <span class="right"><%= @user_edited.fat %></span></p>
              <p class="border-bottom">Tłuszcz trzewny: <span class="right"><%= @user_edited.visceral_fat %></span></p>
              <p class="border-bottom-edit">Typ konta:
                <span class="right">
                  <%= if @user.role == "administrator" do %>
                    <%= text_input f, :role, value:  @user_edited.role, class: "card_edit_input", placeholder: "to pole jest puste" %>
                    <%= error_tag f, :role %>
                  <% else %>
                    <%= @user_edited.role %>
                  <% end %>
                </span>
              </p>
              <p style="line-height: 44px;">Ostatnia aktualizacja: <span class="right"><%= @user_edited.role %></span></p><br>

            </div>
            <div class="card-action grey lighten-4" style="text-align: right">
              <%= submit "Zapisz", to: user_path(@conn, :update, @user_edited.id), class: "btn green accent-4 black-text" %>
              <%= link "Anuluj", to: user_path(@conn, :show, @user_edited.id), class: "btn red darken-1 white-text" %>
            </div>

        </div>

    </div>
    <% end %>
  </div>
</div><br>

web/templates/user/index.html.eex
  <ul class="collection">
    <h2 class="header white-text" style="width: 97%; margin-left: auto; margin-right: auto; text-align: left">
      Lista użytkowników
      <span style="font-size: 2.0rem"><%= if @user.role == "klient" do %>(klienci mają dostęp tylko do własnych kont)<% end %></span>
    </h2>
    <%= for user <- @users do %>
       <%= if @user.role == "administrator" || @user.id == user[:id] do %>
        <li class="collection-item">
          <%= link to: user_path(@conn, :show, user[:id]), class: "btn grey greyh lighten-3 collection-title", style: "" do %>
            <%= "#{user[:id]}: #{user[:first_name]} #{user[:last_name]}" %> <b> <%= "#{user[:email]}" %> </b>
            <%= link "Diety", to: diet_path(@conn, :index, user[:id]), class: "btn green accent-1 black-text waves-effect" %>
            <%= link "Analiza zmian", to: change_path(@conn, :index, user[:id]), class: "btn green accent-1 black-text" %>
            <%= link "Edytuj", to: user_path(@conn, :edit,  user[:id]), class: "btn yellow accent-1 black-text"  %>
            <%= link "Usuń", to: user_path(@conn, :delete, user[:id]), class: "btn  red darken-1 white-text", method: :delete  %>
            <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
  <br>

web/templates/user/new.html.eex
<div class="create_user">
  <h2 class="header white-text">
    Tworzenie nowego konta - podaj adres email
  </h2>

  <div class="center-align">
    <%= form_for @changeset, user_path(@conn, :create), fn f -> %>
    <%= text_input f, :email, placeholder: "email", class: "my-form input-bg", id: "email",
      style: "margin-top: 10px" %>
      <%= error_tag f, :email %>
    <br>
    <button type="submit" class="btn btn-default input-bg">Wyślij</button>
    <% end %>
  </div>

</div>

web/templates/user/password.html.eex
<center>

<h3>Podaj hasło, które otrzymałeś podczas wizyty w gabinecie</h3>

<%= form_for @conn, auth_path(@conn, :login_with_password), [as: :login_pass], fn f -> %>

<div class="form-gen">
  <%= password_input f, :password, placeholder: "hasło", class: "my-form input-bg", id: "password",
   style: "margin-top: 10px" %>
   <%= error_tag f, :password %>
  <br><br>
  <button type="submit" class="btn btn-default input-bg">Wyślij hasło</button>
</div>

<%= hidden_input f, :email, id: "email", value: "#{@conn.assigns.user.email}" %>

<% end %>
<br><br>
<h4>Jeśli nie jesteś naszym klientem a chcesz skożystać z naszych usług, umów się na wizytę:<br><br>

  przez stronę www:
  <a href="http://greenfitdiety.pl/" target="_blank" style="font-size: 1.8rem; font-weight: bold; color: black">
    greenfitdiety.pl
  </a><br><br>
  telefonicznie:  <b class="black-text">500-126-496</b><br><br>
  mailowo: <b class="black-text">ula.bulanda92@gmail.com</b><br>
</h4>

</center>

web/templates/user/settings.html.eex
<div class="edit_user">
  <div class="col s12 m7">
    <%= form_for @conn, user_path(@conn, :update_password, @conn.assigns.user.id), [as: :pswchange], fn f -> %>
    <h2 class="header white-text">
      Ustawienia konta
    </h2>
    <div class="card horizontal">
      <div class="card-image grey lighten-3 center-align valign-wrapper" style="padding: 20px">
        <span style="font-size: 2.1rem">Zmiana hasła</span>
      </div>
        <div class="card-stacked grey lighten-4">
            <div class="card-content">
              <p class="border-bottom-edit">Podaj stare hasło:
                <span class="right">
                  <%= password_input f, :old_password, class: "card_edit_input", placeholder: "podaj stare hasło" %>
                  <%= error_tag f, :old_password %>
                </span>
              </p>
              <p class="border-bottom-edit">Podaj nowe hasło:
                <span class="right">
                  <%= password_input f, :new_password, class: "card_edit_input", placeholder: "podaj nowe hasło" %>
                  <%= error_tag f, :old_password %>
                </span>
              </p>
              <p class="border-bottom-edit">Powtórz nowe hasło:
                <span class="right">
                  <%= password_input f, :new_password_repeat, class: "card_edit_input", placeholder: "powtórz nowe hasło" %>
                  <%= error_tag f, :new_password_repeat %>
                </span>
              </p>
            </div>
            <div class="card-action grey lighten-4" style="text-align: right">
              <%= submit "Zapisz", class: "btn green accent-4 black-text" %>
            </div>
        </div>
    </div>
    <% end %>
  </div>
</div>

web/templates/user/show.html.eex
<div class="show_user">
  <div class="col s12 m7">
    <h2 class="header white-text">
      Karta użytkownika
    </h2>
    <div class="card horizontal">
      <div class="card-image grey lighten-3 center-align" style="padding: 20px">
        <img src="<%= "/files/avatars/" <> @user_showed.email <> ".png" %>" class="shadow"
         style="margin-left: auto; margin-right: auto;"/><br>
        <p><span style="font-size: 2.5rem;"><b><%= @user_showed.first_name %> <%= @user_showed.last_name %> </b></span></p>
        <p><span style="font-size: 2.1rem"><%= @user_showed.email %> </span></p>
      </div>
      <div class="card-stacked grey lighten-4">
        <div class="card-content">
          <p class="border-bottom">ID: <span class="right"><%= @user_showed.id %></span></p>
          <p class="border-bottom">Telefon: <span class="right"><%= @user_showed.phone %></span></p>
          <p class="border-bottom">Waga: <span class="right"><%= @user_showed.weight %></span></p>
          <p class="border-bottom">Wzrost: <span class="right"><%= @user_showed.height %></span></p>
          <p class="border-bottom">Wiek: <span class="right"><%= @user_showed.age %></span></p>
          <p class="border-bottom">Wiek metaboliczny: <span class="right"><%= @user_showed.metabolic_age %></span></p>
          <p class="border-bottom">Zawartość tłuszczu w organiźmie: <span class="right"><%= @user_showed.fat %></span></p>
          <p class="border-bottom">Tłuszcz trzewny: <span class="right"><%= @user_showed.visceral_fat %></span></p>
          <p class="border-bottom">Typ konta: <span class="right"><%= @user_showed.role %></span></p>
          <p style="line-height: 44px;">Ostatnia aktualizacja: <span class="right"><%= @user_showed.role %></span></p>
        </div>
        <div class="card-action grey lighten-4" style="text-align: right">
          <%= link "Diety", to: diet_path(@conn, :index, @user_showed), class: "btn green accent-4 black-text" %>
          <%= link "Analiza zmian", to: change_path(@conn, :index, @user_showed), class: "btn green accent-4 black-text" %>
          <%= link "Edytuj", to: user_path(@conn, :edit, @user_showed), class: "btn yellow accent-1 black-text"  %>
          <%= link "Usuń", to: user_path(@conn, :delete, @user_showed), class: "btn red darken-1 white-text", method: :delete  %>
        </div>
      </div>
    </div>
  </div>
</div><br>